import { UserFormData } from "./types";

export const tabs = [
  "PERSONAL INFORMATION",
  "CONTACT INFORMATION",
  "OFFICE ADDRESS",
  "SOCIAL MEDIA ACCOUNTS",
  "OTHERS",
];

export const defaultFormData: UserFormData = {
  firstname: "",
  middlename: "",
  lastname: "",
  honorificprefix: "",
  honorificsuffix: "",
  jobtitle: "",
  company: "",
  logo: "",
  website: "",
  cellphone: "",
  whatsapp: "",
  viber: "",
  wechat: "",
  workphone: "",
  workemail: "",
  workfax: "",
  address: "",
  location: "",
  linkedin: "",
  facebook: "",
  note: "",
  profileImage: "/profile-placeholder.jpeg",
  street: "",
  city: "",
  state: "",
  postalCode: "",
  country: "",
  factoryLocation: "",
  factoryStreet: "",
  factoryCity: "",
  factoryState: "",
  factoryPostalCode: "",
  factoryCountry: "",
};
